### ISSUE TITLE
Build failure on Ubuntu 10.04 (Lucid Lynx)

### ISSUE THREAD

**Issue by jamesgraves** [mkottman/lqt#5]
The build fails on a stock Ubuntu 10.04 LTS (Lucid Lynx) system with an error message about EasingCurve not being a member of QVariant.  I first tried the build on a Ubuntu 10.10 system, it worked fine and I was able to run some tests on that platform.

Here's the relevant build output on the 10.04 system:

```
[ 15%] Built target cpptoxml
[ 15%] Generating XML: running cpptoxml on qtcore
[ 15%] Built target generate_qtcore_xml
[ 15%] Generating binding code with Lua
[ 16%] Built target generate_qtcore_cpp
[ 17%] Generating qtcore_src/moc_qtcore_slot.cxx
Scanning dependencies of target qtcore
[ 18%] Building CXX object CMakeFiles/qtcore.dir/qtcore_src/qtcore_merged_build.cpp.o
In file included from /usr/local/jgraves/lua/lqt/build/qtcore_src/qtcore_merged_build.cpp:179:
/usr/local/jgraves/lua/lqt/build/qtcore_src/qtcore_meta_QString.cpp: In function 'int lqt_bind_3049(lua_State*)':
/usr/local/jgraves/lua/lqt/build/qtcore_src/qtcore_meta_QString.cpp:1610: warning: format not a string literal and no format arguments
[ 18%] Building CXX object CMakeFiles/qtcore.dir/common/lqt_qt.cpp.o
/usr/local/jgraves/lua/lqt/common/lqt_qt.cpp: In function 'int lqtL_qvariant_value(lua_State*)':
/usr/local/jgraves/lua/lqt/common/lqt_qt.cpp:455: error: 'EasingCurve' is not a member of 'QVariant'
In file included from /usr/include/qt4/QtCore/qvariant.h:48,
                 from /usr/include/qt4/QtCore/QVariant:1,
                 from /usr/local/jgraves/lua/lqt/common/lqt_qt.hpp:8,
                 from /usr/local/jgraves/lua/lqt/common/lqt_qt.cpp:1:
/usr/include/qt4/QtCore/qmetatype.h: In static member function 'static int QMetaTypeId2<T>::qt_metatype_id() [with T = QEasingCurve]':
/usr/include/qt4/QtCore/qmetatype.h:210:   instantiated from 'int qMetaTypeId(T*) [with T = QEasingCurve]'
/usr/include/qt4/QtCore/qvariant.h:459:   instantiated from 'void qVariantSetValue(QVariant&, const T&) [with T = QEasingCurve]'
/usr/include/qt4/QtCore/qvariant.h:525:   instantiated from 'void QVariant::setValue(const T&) [with T = QEasingCurve]'
/usr/local/jgraves/lua/lqt/common/lqt_qt.cpp:336:   instantiated from here
/usr/include/qt4/QtCore/qmetatype.h:200: error: 'qt_metatype_id' is not a member of 'QMetaTypeId<QEasingCurve>'
make[2]: *** [CMakeFiles/qtcore.dir/common/lqt_qt.cpp.o] Error 1
make[1]: *** [CMakeFiles/qtcore.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by mkottman** [comment]
It looks like my fault, the wrapper for QVariant::value() was written by hand. What version of Qt are you using in stock Lua? Please post the result of `qmake --version`.

**Comment by jamesgraves** [comment]
Versions:

> Lua 5.1.4  Copyright (C) 1994-2008 Lua.org, PUC-Rio
> 
> QMake version 2.01a
> 
> Using Qt version 4.6.2 in /usr/lib

**Comment by mkottman** [comment]
Right, well, I was doing the QVariant subtypes for Qt 4.7.0, which I have installed on my Ubuntu 10.10. I will try to modify it to match "at least 4.6" according to [this list](http://doc.qt.nokia.com/4.6/qmetatype.html)

**Comment by mkottman** [comment]
Fixed in [this commit](https://github.com/mkottman/lqt/commit/c9e368668fe01b6338a01ab5f2dbf15196147927)

**Comment by jamesgraves** [comment]
Great, thanks.
